# Note: Use same db for development and production for sample demo.

development:
  adapter: sqlite3
  database: db/links.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/links.sqlite3
  pool: 5
  timeout: 5000
